server:
  port: 8080

spring:
  shell:
    interactive:
      enabled: true
    script:
      enabled: false

  datasource:
    url: jdbc:mysql://localhost:3306/e_ticket?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        show_sql: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

userConfig:
  configFilePath: userConfig.json


logging:
  file:
    name: logs/application.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"  # Customize log format
    console: ""                 # Disable console logging by setting it to an empty string

